name: Deploy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy-infra:
    name: Terraform Deploy Infra
    runs-on: ubuntu-latest
    environment: prod
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

      TF_VAR_project_name: "hylastix-candidate-test"
      TF_VAR_region: "westeurope"
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_address_space: '["10.0.0.0/20"]'
      TF_VAR_subnets: '[{"name":"private-runner-subnet","address_prefix":"10.0.0.0/24"},{"name":"private-app-subnet","address_prefix":"10.0.1.0/24"},{"name":"appgw-subnet","address_prefix":"10.0.2.0/24"}]'

      TF_VAR_runner_vm_size: Standard_B2s
      TF_VAR_runner_vm_admin_username: ${{ secrets.RUNNER_VM_ADMIN_USERNAME }}
      TF_VAR_runner_vm_ssh_public_key: ${{ secrets.RUNNER_SSH_PUBLIC_KEY }}
      TF_VAR_runner_github_url: https://github.com/${{ github.repository }}
      TF_VAR_app_vm_size: Standard_B2s
      TF_VAR_app_vm_admin_username: ${{ secrets.APP_VM_ADMIN_USERNAME }}
      TF_VAR_app_vm_ssh_public_key: ${{ secrets.APP_SSH_PUBLIC_KEY }}

    defaults:
      run:
        working-directory: infra/terraform

    outputs:
      app_vm_private_ip: ${{ steps.tf-outputs.outputs.app_vm_private_ip }}
      appgw_public_ip: ${{ steps.tf-outputs.outputs.appgw_public_ip }}

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get GitHub self-hosted runner token
        id: get-runner-token
        run: |
          TOKEN_JSON=$(curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token)
          
          REG_TOKEN=$(echo "$TOKEN_JSON" | jq -r '.token')
          echo "runner_token=$REG_TOKEN" >> $GITHUB_OUTPUT

      - name: Initialize and Plan Terraform
        env:
          TF_VAR_runner_registration_token: ${{ steps.get-runner-token.outputs.runner_token }}
        run: |
          terraform init -input=false
          terraform plan -input=false

      - name: Apply Terraform
        env:
          TF_VAR_runner_registration_token: ${{ steps.get-runner-token.outputs.runner_token }}
        run: terraform apply -auto-approve

      - name: Export Terraform Outputs
        id: tf-outputs
        run: |
          echo "app_vm_private_ip=$(terraform output -raw app_vm_private_ip)" >> $GITHUB_OUTPUT
          echo "appgw_public_ip=$(terraform output -raw appgw_public_ip)" >> $GITHUB_OUTPUT

  next-job:
    runs-on: [self-hosted, Linux, X64]
    needs: terraform-deploy-infra
    env:
      VM_IP: ${{ needs.terraform-deploy-infra.outputs.app_vm_private_ip }}
      VM_USER: ${{ secrets.APP_VM_ADMIN_USERNAME }}
      SSH_KEY_PATH: /tmp/app_vm_key
    steps:
      - name: Print previous job outputs and test SSH
        run: |
          echo "App VM IP: $VM_IP"
          echo "AppGW IP: ${{ needs.terraform-deploy-infra.outputs.appgw_public_ip }}"

          echo "${{ secrets.APP_VM_PRIVATE_KEY }}" > "$SSH_KEY_PATH"
          chmod 600 "$SSH_KEY_PATH"
          ssh -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$VM_USER"@"$VM_IP" "hostname && uptime"

      - name: Setup Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip3 install --upgrade ansible
          ansible --version

      - name: Install required Ansible roles
        run: |
          ansible-galaxy install geerlingguy.docker
          ansible-galaxy collection install community.docker

      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Run Docker Setup playbook
        run: |
          ansible-playbook -vvv \
                           -i "$VM_IP," \
                           -u "$VM_USER" \
                           --private-key "$SSH_KEY_PATH" \
                           infra/ansible/playbooks/setup_docker.yaml

      - name: Run App Stack playbook
        env:
          KEYCLOAK_IMAGE: quay.io/keycloak/keycloak:21.1.1
          KEYCLOAK_ADMIN_USER: ${{ secrets.KEYCLOAK_ADMIN_USER }}
          KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          POSTGRES_IMAGE: postgres:15
          POSTGRES_DB_NAME: appdb
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          WEB_IMAGE: nginx:latest
          WEB_CONTENT_DIR_LOCAL: ../web_content/
          WEB_CONFIG_DIR_LOCAL: ../web_config/
          WEB_PORT: 8080
          OAUTH2_PROXY_IMAGE: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
          OAUTH2_PROXY_COOKIE_SECRET: ${{ secrets.OAUTH2_PROXY_COOKIE_SECRET }}
          
        run: |
          ansible-playbook -vvv \
                           -i "$VM_IP," \
                           -u "$VM_USER" \
                           --private-key "$SSH_KEY_PATH" \
                           infra/ansible/playbooks/deploy_stack.yaml \
                           --extra-vars "keycloak_image=$KEYCLOAK_IMAGE \
                                         keycloak_admin_user=$KEYCLOAK_ADMIN_USER \
                                         keycloak_admin_password=$KEYCLOAK_ADMIN_PASSWORD \
                                         keycloak_client_secret=$KEYCLOAK_CLIENT_SECRET \
                                         postgres_image=$POSTGRES_IMAGE \
                                         postgres_db_name=$POSTGRES_DB_NAME \
                                         postgres_user=$POSTGRES_USER \
                                         postgres_password=$POSTGRES_PASSWORD \
                                         web_image=$WEB_IMAGE \
                                         web_content_dir_local=$WEB_CONTENT_DIR_LOCAL \
                                         nginx_config_dir_local=$WEB_CONFIG_DIR_LOCAL \
                                         web_port=$WEB_PORT \
                                         oauth2_proxy_image=$OAUTH2_PROXY_IMAGE \
                                         oauth2_proxy_cookie_secret=$OAUTH2_PROXY_COOKIE_SECRET"
                                         